Merge from DLPX-75209 into 6.0/stage to test the fix for DLPX-75209 on 6.0/stage branch  (#2)
* 6.0/stage (#1)

* DLPX-78449 [Backport of DLPX-78424 to 6.0.13.0] Increase ulimit for open files

* DLPX-77850 Bump zvol threads count from 32 to 256

* Fix for DLPX-75209 rebooting a Delphix Engine in AWS can leave the system with no network configuration

Co-authored-by: Tony Nguyen <Tony.Nguyen@delphix.com>

* Update update_netplan_to_mac_address

Fixed errors from the check-shellcheck script.

* Update update_netplan_to_mac_address

* Update update_netplan_to_mac_address

Makes changes suggested by shfmt script.

* Update postinst

Update postinst based on comments from shfmt script

* Update update_netplan_to_mac_address

Update update_netplan_to_mac_address based on comments from shellcheck script

* Update update_netplan_to_mac_address

Update update_netplan_to_mac_address script to follow shellcheck and sgfmt guidelines.

* Update update_netplan_to_mac_address

Update update_netplan_to_mac_address to follow shellcheck guidelines.

* Update and rename 20-override.conf to aws-override.conf

The 20-override.conf file has been renamed to a more meaningful name "aws-override.conf". The new name communicates the intent that this file is specific to AWS behavior. 
An empty "ExecStartPre=" directive resets any previous ExecStartPre= directives. This behavior is not needed and was added due to some misunderstanding on my part. Hence, I have removed this empty "ExecStartPre=" directive.

Co-authored-by: Tony Nguyen <Tony.Nguyen@delphix.com>

diff --git a/files/aws/usr/bin/update_netplan_to_mac_address b/files/aws/usr/bin/update_netplan_to_mac_address
--- a/files/aws/usr/bin/update_netplan_to_mac_address
+++ b/files/aws/usr/bin/update_netplan_to_mac_address
@@ -14,13 +14,11 @@
 
 INTERFACE_TO_MACADDRESS_MAP_FILE="/etc/interface_to_macaddress_map.out"
 DLPX_NETPLAN_FILE="/etc/netplan/10-delphix.yaml"
-UPGRADE_PROPERTIES_FILE="/var/dlpx-update/upgrade.properties"
 SYSFS_NET_DIRECTORY="/sys/class/net"
 
-function die()
-{
-  echo "$(basename $0): $@" >&2
-  exit 1
+function die() {
+	echo "$(basename "$0"): $*" >&2
+	exit 1
 }
 
 # We want to process the map file only when we boot into the new version post upgrade, and not during
@@ -29,29 +27,29 @@ function die()
 # 1. Existence of the map file, which is generated during the upgrade processing.
 # 2. Existence of mac address based network interface filenames under the /sys/class/net heirarchy.
 # 3. The netplan file /etc/netplan/10-delphix.yaml should not contain mac address based interface names.
-if [[ -e "$INTERFACE_TO_MACADDRESS_MAP_FILE" ]] &&\
-  find "$SYSFS_NET_DIRECTORY" -regextype egrep -regex '.*enx[a-z0-9]{12}$' | read &&\
-  ! egrep 'enx[a-z0-9]{12}' "$DLPX_NETPLAN_FILE"; then
-  # save the existing netplan file before updating it, could be handy for debugging
-  cur_timestamp=$(date +%y%m%d_%h%m%s)
-  cp -p "$DLPX_NETPLAN_FILE" /var/tmp/"$DLPX_NETPLAN_FILE"_"$cur_timestamp"
+if [[ -e "$INTERFACE_TO_MACADDRESS_MAP_FILE" ]] &&
+	find "$SYSFS_NET_DIRECTORY" -regextype egrep -regex '.*enx[a-z0-9]{12}$' | read -r &&
+	! grep -E 'enx[a-z0-9]{12}' "$DLPX_NETPLAN_FILE"; then
+	# save the existing netplan file before updating it, could be handy for debugging
+	cur_timestamp=$(date +%y%m%d_%h%m%s)
+	cp -p "$DLPX_NETPLAN_FILE" /var/tmp/"$DLPX_NETPLAN_FILE"_"$cur_timestamp"
 
-  # Update the netplan file with MAC based interface names
-  while IFS= read -r line; do
-    ifname=$(echo $line | awk '{print $1}')
-    macname=$(echo $line | awk '{print $2}')
-    macname1="enx""$macname"
-    echo "Modifying $ifname to $macname1 in the netplan file" >>/var/log/syslog 2>&1
-    grep -n "$ifname" "$DLPX_NETPLAN_FILE" || die "Did not find $ifname in netplan file"
-    sed -i "s/$ifname/$macname1/g" "$DLPX_NETPLAN_FILE" || \
-      die "Could not modify $ifname to $macname in the netplan file"
-  done < "$INTERFACE_TO_MACADDRESS_MAP_FILE"
-  echo "Updated all the interface names to mac address based names" >>/var/log/syslog 2>&1
+	# Update the netplan file with MAC based interface names
+	while IFS= read -r line; do
+		ifname=$(echo "$line" | awk '{print $1}')
+		macname=$(echo "$line" | awk '{print $2}')
+		macname1="enx""$macname"
+		echo "Modifying $ifname to $macname1 in the netplan file" >>/var/log/syslog 2>&1
+		grep -n "$ifname" "$DLPX_NETPLAN_FILE" || die "Did not find $ifname in netplan file"
+		sed -i "s/$ifname/$macname1/g" "$DLPX_NETPLAN_FILE" ||
+			die "Could not modify $ifname to $macname in the netplan file"
+	done <"$INTERFACE_TO_MACADDRESS_MAP_FILE"
+	echo "Updated all the interface names to mac address based names" >>/var/log/syslog 2>&1
 
-  # After updating the netplan file, we must call "netplan generate" to generate new link files under
-  # /run/systemd/network which will be consumed by the systemd-networkd to bring up the network interfaces
-  netplan generate || die "Failed to run netplan generate command"
+	# After updating the netplan file, we must call "netplan generate" to generate new link files under
+	# /run/systemd/network which will be consumed by the systemd-networkd to bring up the network interfaces
+	netplan generate || die "Failed to run netplan generate command"
 
-  # prevent conversion attempts on subsequent reboots
-  rm "$INTERFACE_TO_MACADDRESS_MAP_FILE" || die "Failed to remove the $INTERFACE_TO_MACADDRESS_MAP_FILE file"
+	# prevent conversion attempts on subsequent reboots
+	rm "$INTERFACE_TO_MACADDRESS_MAP_FILE" || die "Failed to remove the $INTERFACE_TO_MACADDRESS_MAP_FILE file"
 fi
